//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFA_TCMB_Doviz_Kuru.Languages {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFA_TCMB_Doviz_Kuru.Languages.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Hakkında benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BİRLEŞİK ARAP EMİRLİKLERİ DİRHEMİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AED {
            get {
                return ResourceManager.GetString("AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tutar: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AVUSTURYA ŞİLİNİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ATS {
            get {
                return ResourceManager.GetString("ATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AVUSTRALYA DOLARI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AUD {
            get {
                return ResourceManager.GetString("AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AZERBAYCAN YENİ MANATI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AZN {
            get {
                return ResourceManager.GetString("AZN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Efektif Alış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BanknoteBuying {
            get {
                return ResourceManager.GetString("BanknoteBuying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Efektif Satış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BanknoteSelling {
            get {
                return ResourceManager.GetString("BanknoteSelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BELÇİKA FRANGI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BEF {
            get {
                return ResourceManager.GetString("BEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BULGAR LEVASI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BGL {
            get {
                return ResourceManager.GetString("BGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BULGAR LEVASI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BGN {
            get {
                return ResourceManager.GetString("BGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KANADA DOLARI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CAD {
            get {
                return ResourceManager.GetString("CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İSVİÇRE FRANGI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CHF {
            get {
                return ResourceManager.GetString("CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÇİN YUANI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CNY {
            get {
                return ResourceManager.GetString("CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dönüştür benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çapraz Kur Diğer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CrossRateOther {
            get {
                return ResourceManager.GetString("CrossRateOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çapraz Kur USD benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CrossRateUSD {
            get {
                return ResourceManager.GetString("CrossRateUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Para Birimi Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Para Birimi Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CurrencyName {
            get {
                return ResourceManager.GetString("CurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Para Birimi Adı (İngilizce) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CurrencyNameEnglish {
            get {
                return ResourceManager.GetString("CurrencyNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tarih: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tarih hafta sonu veya resmi tatil olabilir! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DateAWeekend {
            get {
                return ResourceManager.GetString("DateAWeekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ALMAN MARKI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DEM {
            get {
                return ResourceManager.GetString("DEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DANİMARKA KRONU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DKK {
            get {
                return ResourceManager.GetString("DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AVRUPA PARA BİRİMİ (ECU) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ECU {
            get {
                return ResourceManager.GetString("ECU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İSPANYOL PEZETASI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ESP {
            get {
                return ResourceManager.GetString("ESP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EURO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EUR {
            get {
                return ResourceManager.GetString("EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FİN MARKKASI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FIM {
            get {
                return ResourceManager.GetString("FIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Döviz Alış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ForexBuying {
            get {
                return ResourceManager.GetString("ForexBuying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Döviz Satış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ForexSelling {
            get {
                return ResourceManager.GetString("ForexSelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FRANSIZ FRANGI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FRF {
            get {
                return ResourceManager.GetString("FRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaynak Para Birimi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SURIYE LİRASI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FYP {
            get {
                return ResourceManager.GetString("FYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İNGİLİZ STERLİNİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GBP {
            get {
                return ResourceManager.GetString("GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genel Ayarlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Git benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YUNAN DRAHMİSİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GRD {
            get {
                return ResourceManager.GetString("GRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yardım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İRLANDA LİRASI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IEP {
            get {
                return ResourceManager.GetString("IEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YENİ ISRAIL ŞEKELİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ILS {
            get {
                return ResourceManager.GetString("ILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İRAN RİYALİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IRR {
            get {
                return ResourceManager.GetString("IRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İTALYAN LİRASI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ITL {
            get {
                return ResourceManager.GetString("ITL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜRDÜN DİNARI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string JOD {
            get {
                return ResourceManager.GetString("JOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAPON YENİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string JPY {
            get {
                return ResourceManager.GetString("JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GÜNEY KORE WONU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KRW {
            get {
                return ResourceManager.GetString("KRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KUVEYT DİNARI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KWD {
            get {
                return ResourceManager.GetString("KWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dil: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LÜKSEMBURG FRANGI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LUF {
            get {
                return ResourceManager.GetString("LUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bülten No: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NewsletterNo {
            get {
                return ResourceManager.GetString("NewsletterNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOLLANDA FLORİNİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NLG {
            get {
                return ResourceManager.GetString("NLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NORVEÇ KRONU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NOK {
            get {
                return ResourceManager.GetString("NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tamam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Güncelleme Yöneticisini Aç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OpenUpdateManager {
            get {
                return ResourceManager.GetString("OpenUpdateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seçenekler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PAKİSTAN RUPİSİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PKR {
            get {
                return ResourceManager.GetString("PKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PORTEKİZ ESKUDOSU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PTE {
            get {
                return ResourceManager.GetString("PTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KATAR RİYALİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string QAR {
            get {
                return ResourceManager.GetString("QAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yenile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RUMEN LEYİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ROL {
            get {
                return ResourceManager.GetString("ROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RUMEN LEYİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RON {
            get {
                return ResourceManager.GetString("RON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RUS RUBLESİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RUB {
            get {
                return ResourceManager.GetString("RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SUUDİ ARABİSTAN RİYALİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SAR {
            get {
                return ResourceManager.GetString("SAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İSVEÇ KRONU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SEK {
            get {
                return ResourceManager.GetString("SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belirtilen tarih hafta sonu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SpecifiedAWeekend {
            get {
                return ResourceManager.GetString("SpecifiedAWeekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Para Birimini Değiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SwitchCurrency {
            get {
                return ResourceManager.GetString("SwitchCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SURIYE LİRASI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SYP {
            get {
                return ResourceManager.GetString("SYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Türkiye Cumhuriyet Merkez Bankası - Döviz Kuru benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TCMB {
            get {
                return ResourceManager.GetString("TCMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   15:30 Tarihinde benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TCMB_Warning {
            get {
                return ResourceManager.GetString("TCMB_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belirlenen Gösterge Niteliğindeki Türkiye Cumhuriyet Merkez Bankası Kurları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TCMB_Warning2 {
            get {
                return ResourceManager.GetString("TCMB_Warning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İstenilen Para Birimi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Araçlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Birim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ABD DOLARI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sürüm benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÖZEL ÇEKME HAKKI (SDR) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string XDR {
            get {
                return ResourceManager.GetString("XDR", resourceCulture);
            }
        }
    }
}
